[workspace]
members = [
  "llvm-ret",
  "llvm-print",
  "llvm-global-vars",
  "llvm-local-vars",
  "llvm-scope",
  "llvm-if-else",
  "llvm-loop",
  "llvm-function",
  "llvm-structs",
  "llvm-structs-heap"
]
